# Generated by Django 3.2.12 on 2022-08-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie_tekst', models.CharField(max_length=200)),
                ('data_publ', models.DateTimeField(verbose_name='data opublikowania ankiety')),
            ],
        ),
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybory_tekst', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankiety.pytanie')),
            ],
        ),
    ]
